import Head from 'next/head';
import 'normalize.css';
import store from '@/store';
// import pokemon from './pokemon/ssr/[name]';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { Provider } from 'react-redux';
import Link from 'next/link';
import Layout from '@/components/layout';
export default function Home() {
  return (
    <Layout home>
      <Head>
        <title>MaLab</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <ul>
          <li>
            Bulbasaur{' '}
            <Link href={{ pathname: '/pokemon/bulbasaur' }}>dynamic</Link>{' '}
            <Link href={{ pathname: '/pokemon/ssr/bulbasaur' }}>SSR</Link>{' '}
            <Link href="/pokemon/ssg/bulbasaur">SSG</Link>
          </li>
          <pokemon />

          <li>
            Beedrill <Link href="/pokemon/beedrill">dynamic</Link>{' '}
            <Link href="/pokemon/ssr/beedrill">SSR</Link>{' '}
            <Link href="/pokemon/ssg/beedrill"> fallback SSG</Link>
          </li>
        </ul>
      </main>
    </Layout>
  );
}
export const getServerSideProps = async ({ locale }) => ({
  props: {
    ...(await serverSideTranslations(locale, ['common'])),
  },
});
