import Head from 'next/head';
import Image from 'next/image';

import styles from '@/styles/Home.module.css';
import { lazy, Suspense } from 'react';
import SideBar from '@/components/Footer';

import About from './about';
import Team from './team';
import Publication from './publication';
import Style from './style';
import Project from './project';

import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
export default function Home() {
  return (
    <>
      <Head>
        <title>MaLab</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main></main>
    </>
  );
}
export const getServerSideProps = async ({ locale }) => ({
  props: {
    ...(await serverSideTranslations(locale, ['common'])),
  },
});
