import Head from 'next/head';
import 'normalize.css';
import store from '@/store';
// import pokemon from './pokemon/ssr/[name]';
import nextI18nextConfig from 'next-i18next.config';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';

import Layout from '@/components/layout';
export default function Home(props) {
  return (
    <div>
      <Head>
        <title>MaLab</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main></main>
    </div>
  );
}
export const getServerSideProps = async ({ locale }) => ({
  props: {
    ...(await serverSideTranslations(locale, ['common'], nextI18nextConfig)),
  },
});
